//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanqueLogicLayer.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie
    {
        public Categorie()
        {
            this.Operations = new HashSet<Operation>();
            this.OperationsPlanning = new HashSet<OperationPlanning>();
        }
    
        public int categorie_id { get; set; }
        public string categorie_nom { get; set; }
        public bool categorie_actif { get; set; }
        public int utilisateur_user_id { get; set; }
    
        public virtual ICollection<Operation> Operations { get; set; }
        public virtual ICollection<OperationPlanning> OperationsPlanning { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
