//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanqueLogicLayer.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compte
    {
        public Compte()
        {
            this.Operations = new HashSet<Operation>();
            this.OperationsPlanning = new HashSet<OperationPlanning>();
        }
    
        public int compte_id { get; set; }
        public string compte_numero { get; set; }
        public int organisme_organisme_id { get; set; }
        public int utilisateur_user_id { get; set; }
        public double compte_interet { get; set; }
        public System.DateTime compte_dateOuverture { get; set; }
        public double compte_soldeDepart { get; set; }
        public double compte_soldeCourant { get; set; }
        public string compte_nom { get; set; }
    
        public virtual Organisme Organisme { get; set; }
        public virtual ICollection<Operation> Operations { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual ICollection<OperationPlanning> OperationsPlanning { get; set; }
    }
}
