//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanqueLogicLayer.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int operation_id { get; set; }
        public double operation_montant { get; set; }
        public System.DateTime operation_date { get; set; }
        public int compte_compte_id { get; set; }
        public int categorie_categorie_id { get; set; }
    
        public virtual Compte Compte { get; set; }
        public virtual Categorie Categorie { get; set; }
    }
}
