//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanqueLogicLayer.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisme
    {
        public Organisme()
        {
            this.Comptes = new HashSet<Compte>();
        }
    
        public int organisme_id { get; set; }
        public string organisme_nom { get; set; }
        public bool organisme_actif { get; set; }
        public string organisme_abrev { get; set; }
    
        public virtual ICollection<Compte> Comptes { get; set; }
    }
}
